create table if not exists public.orders (
  id bigint generated by default as identity not null,
  name text null,
  phone text null,
  address text null,
  product text null,
  color text null,
  quantity bigint null,
  price bigint null,
  shipping_amount bigint null,
  total_amount bigint null,
  status text null default 'pending'::text,
  created_at timestamp with time zone not null default now(),
  constraint orders_pkey primary key (id)
);

alter table public.orders add column if not exists color text null;
alter table public.orders disable row level security;
